gemfile: "test/dummy/Gemfile"
language: ruby
script:
- cd test/dummy
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake db:test:prepare
- bundle exec rake spec
rvm:
  - "1.9.3"
  - "2.0.0"